### ISSUE TITLE
Version 2.0.3 not available on git nor packagist

### ISSUE THREAD

**Issue by JeremyMancel** [Cidaas/Cidaas-for-Typo3#4]
The 2.0.3 version is only available on the extensions.typo3.org site. Therefore, if you are using typo3 with composer mode on, you cannot install it.

Could you add it to packagist ? 
Thanks.

**Comment by sawi** [comment]
@JeremyMancel thanks for your ticket. We will check if it is possible to publish our plugin on packagist too.

**Comment by sawi** [comment]
@JeremyMancel version 2.0.3 is now also available on packagist.
