### ISSUE TITLE
Error: refresh_token cannot be null

### ISSUE THREAD

**Issue by ulrichmathes** [Cidaas/Cidaas-for-Typo3#7]
We get an error on login when user is not already persisted in database. The insert statement wants to set `refresh_token` as `null` which is not permitted via ext_tables.sql.

> An exception occurred while executing 'INSERT INTO `fe_users` ...
> Column 'refresh_token' cannot be null
https://github.com/Cidaas/Cidaas-for-Typo3/blob/8fcae535df7dd0f92114737cf2395630b0c498da/ext_tables.sql#L7

Here all data for the possible new user is collected. I don't know why there is no `refresh_token` available.
https://github.com/Cidaas/Cidaas-for-Typo3/blob/8fcae535df7dd0f92114737cf2395630b0c498da/Classes/Service/AuthenticationService.php#L324

In my opinion there are two solutions depending on if a `refresh_token` is mandatory.
a) check for missing `refresh_token` and throw an error
b) let `refresh_token = null` via ext_tables.sql

**Comment by tujit** [comment]
Version [v2.0.4](https://packagist.org/packages/cidaas/cidaas-for-typo3#v2.0.4) released with the fix. Thank you for informing us about the bug. Appreciate your support!!
